### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by fchapoton**
found using codespell

### CODE REVIEW

**Comment by lpsinger** [comment]
@fchapoton, these Fortran codes are copies of https://ccmc.gsfc.nasa.gov/models/modelinfo.php?model=IGRF and https://ccmc.gsfc.nasa.gov/models/modelinfo.php?model=AE-8/AP-8%20RADBELT. I am trying to make as few changes as possible to them in my own source tree. Would you please report these typos to the maintainers of those codes listed on their respective pages?

**Comment by fchapoton** [comment]
Ok, understood. But if they have no github repository, I have not the least idea about how to report these typos.

**Comment by lpsinger** [comment]
Just email the points of contact listed on those pages.

**Comment by fchapoton** [comment]
ok, mails sent. Likely to be ignored, in my opinion.

**Comment by lpsinger** [comment]
Maybe, maybe not. I sent them some small bug fixes and they accepted them.

**Pull request closed without merging**
